security:
  oauth2:
    client:
      clientId: overwrite-me
      clientSecret: overwrite-me
      accessTokenUri: https://login.eveonline.com/oauth/token
      userAuthorizationUri: https://login.eveonline.com/oauth/authorize
    resource:
      userInfoUri: https://login.eveonline.com/oauth/verify
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pve?verifyServerCertificate=false&useSSL=false&requireSSL=false&characterEncoding=UTF-8
    username: pve
    password: pve
server:
  session:
    timeout: 10800
    