on:
  push:
    branches:
      - master
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven package phase
        run: mvn --batch-mode --update-snapshots package
