steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      java-version: '24'
      distribution: 'temurin'
  - name: Run the Maven package phase
    run: mvn --batch-mode --update-snapshots package
